version: '3'

services:
  db-dev:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
      - '3333:3306'

  db-admin:
    image: phpmyadmin:latest
    ports:
      - '80:80'
    environment:
      PMA_HOST: db-dev
      MYSQL_ROOT_PASSWORD: root
